
try { client.main.init(); } catch (e) { console.error("An error occurred when calling (client.main/init)"); console.error(e); }